# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: burden.cc
description: I've been a contributing netizen since 1998, when it was common to use a self appointed handle. Paying homage to the lessons of duality, &quot;burden&quot; always seemed appropriate as a reminder to stay humble.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
keybase_username: burden
github:
  username: burden
  repo: burdendotcc
email-key: PDjVWvBdECAURGxYo96mqHJ73T5M1Qt4pw0ZNrhOLsflnicFazgeSIyX8Kubk2
email-encoded: K1@CEzmD8.uu

# seo-tag settings
logo: burdencc-logo.png # will be shown in json+ld/publisher@Organization
author: 
  twitter: cheapexcitement # author's twitter handle
  name: burden
twitter:
  username: cheapexcitement # site's twitter handle
  image: /assets/social-twitter-card.jpg # for src/_layouts/default.html
social:
  links:
    - https://twitter.com/cheapexcitement
    - https://github.com/burden
    - https://keybase.io/burden

# Build settings
source: src
destination: www

# options for src/_layouts/compress.html
compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

#options for jekyll-assets
assets:
  sources:
  - _assets/vendor
  digest: true
  compression: true
  gzip: true
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: true
    js: uglifier

highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

plugins:
  - jekyll-assets
  - kramdown
  - uglifier
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 4
paginate_path: /blog/:num/
permalink: /blog/:categories/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: 
        path: assets/social-open-graph.jpg
      
include:
  - CNAME
